language: php
php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer install

script:
  - ./vendor/bin/phpunit --testdox

after_script:
  - vendor/bin/test-reporter

addons:
    code_climate:
        repo_token: 6ddc69817dac07e1354bc81cb196703490728693518ab2dae62d03e2fa3dca93
