services:
    concerto.soloist:
        class: %concerto.soloist_class%
        scope: request
        synthetic: true
        synchronized: true

    concerto.listener.find_soloist:
        class: Ctrl\Bundle\ConcertoBundle\EventListener\FindSoloistListener
        arguments:
            - @service_container
            - @event_dispatcher
            - @concerto.solo
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onEarlyKernelRequest, priority: 1  }

    concerto.listener.conduct_soloist:
        class: Ctrl\Bundle\ConcertoBundle\EventListener\ConductSoloistListener
        arguments:
            - @doctrine.orm.entity_manager
            - %concerto.soloist_class%
        tags:
            - { name: kernel.event_listener, event: soloist.found, method: onSoloistFound }

    concerto.subscriber.claim_entity:
        class: Ctrl\Bundle\ConcertoBundle\EventListener\ClaimEntitySubscriber
        tags:
            - { name: doctrine.event_subscriber }

    concerto.soloist_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - %concerto.soloist_class%
